name: Update ATV Stream URL

on:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir
  workflow_dispatch:  # Manuel tetikleme için

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node bot.js
