name: M3U8 Yakalayici

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  calistir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Skip Chromium Download
        env:
          PUPPETEER_SKIP_DOWNLOAD: 'true'
        run: npm ci
      - name: Botu Atesle
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node bot.js
